#!/bin/sh
set -e
cd "$(dirname "${0}")/.."

./scripts/build

echo "--> Running Docker container"
docker run \
  --rm \
  --interactive \
  --tty \
  --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  --volume "${PWD}/tlpi=/tlpi" \
  --name tlpi \
  tlpi
